FROM node:11 as build-env
WORKDIR /usr/src/app
COPY ./package.json ./
RUN npm install
COPY ./ .
RUN npm run build:prod

# Build runtime image
FROM nginx:latest
COPY --from=build-env /usr/src/app/dist /usr/share/nginx/html
COPY ./nginx.conf /etc/nginx/nginx.conf